/*
 * This file is generated by jOOQ.
*/
package io.noorulhaq.functional.banking.domain.model.jooq;


import io.noorulhaq.functional.banking.domain.model.jooq.tables.Accounts;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in BANKING
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>BANKING.ACCOUNTS</code>.
     */
    public static final Accounts ACCOUNTS = io.noorulhaq.functional.banking.domain.model.jooq.tables.Accounts.ACCOUNTS;
}
